version: '3.8'

services:
    postgres:
      image: postgres:15-alpine
      environment:
        - DATABASE_URL= ${DATABASE_URL}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 30s
        timeout: 10s
        retries: 5
      networks:
        - socket-hub-network

      auth-service:
        build:
          context: ./services/auth-service
          dockerfile: Dockerfile
        environment:
          -DATABASE_URL=${DATABASE_URL}
        depends_on:
          postgres:
            condition: service_healthy
        networks:
          -socket-hub-network

    api-gateway:
      build:args:
        context: ./services/api-gateway
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
      environment:
        - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      depends_on:
        - auth-service
      networks:
        - socket-hub-network



networks:
  socket-hub-network:
    driver: bridge

volumes: